config/routes.rb
Rserv::Application.routes.draw do
  resources :users

  resources :pics

  get "welcome/index"

   root 'pics#index'

  get 'get/:sender' => 'pics#multi'
  get 'hello/:pin' => 'users#hello'
  get 'hello_new' => 'users#hello_new'
  post 'hello/:pin' => 'users#hello_create'

  

end

app/models/pic.rb
class Pic < ActiveRecord::Base
	def self.all_except(sender)
    find(:all, :order=> "random()", :conditions => ["sender != ?", sender]).first(20)
  end
end

app/models/user.rb
class User < ActiveRecord::Base
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/pics_controller.rb
class PicsController < ApplicationController
  before_action :set_pic, only: [:show, :edit, :update, :destroy]
  skip_before_action :verify_authenticity_token


  # GET /pics
  # GET /pics.json
  def index
    @pics = Pic.all
  end

  def multi
    @pics = Pic.all_except(params[:sender])
  
  end

  # GET /pics/1
  # GET /pics/1.json
  def show
  end

  # GET /pics/new
  def new
    @pic = Pic.new
  end

  # GET /pics/1/edit
  def edit
  end

  # POST /pics
  # POST /pics.json
  def create
    @pic = Pic.new(pic_params)

    respond_to do |format|
      if @pic.save
        format.html { redirect_to @pic, notice: 'Pic was successfully created.' }
        format.json { render action: 'show', status: :created, location: @pic }
      else
        format.html { render action: 'new' }
        format.json { render json: @pic.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /pics/1
  # PATCH/PUT /pics/1.json
  def update
    respond_to do |format|
      if @pic.update(pic_params)
        format.html { redirect_to @pic, notice: 'Pic was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @pic.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /pics/1
  # DELETE /pics/1.json
  def destroy
    @pic.destroy
    respond_to do |format|
      format.html { redirect_to pics_url }
      format.json { head :no_content }
    end
  end


  private
    # Use callbacks to share common setup or constraints between actions.
    def set_pic
      @pic = Pic.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def pic_params
      params.fetch(:pic, {}).permit(:src, :mot, :sender)
      #puts params.to_json 
    end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :set_user, only: [:show, :edit, :update, :destroy]

  # GET /users
  # GET /users.json
  def index
    @users = User.all
  end

  # GET /users/1
  # GET /users/1.json
  def show
  end

  # GET /users/new
  def new
    @user = User.new
  end

  ########## HELLO && HELLO NEW , thx github.com/subroot :* #############
  def hello
    @user = User.where(pin: params[:pin]).first   
    if !@user.blank?
      render :hello
    else
      redirect_to hello_new_path(pin: params[:pin])
    end
  end
  
  def hello_new
    if params[:pin]
      @pin = params[:pin]
    end
    @user = User.new
  end    
 
  def hello_create
    @user = User.new(user_params)
 
    respond_to do |format|
      if @user.save
        format.html { redirect_to @hello, notice: 'User was successfully created.' }
        format.json { render action: 'hello', status: :created, location: @hello }
      else
        format.html { render action: 'new' }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end  


  # GET /users/1/edit
  def edit
  end

  # POST /users
  # POST /users.json
  def create
    @user = User.new(user_params)

    respond_to do |format|
      if @user.save
        format.html { redirect_to @user, notice: 'User was successfully created.' }
        format.json { render action: 'show', status: :created, location: @user }
      else
        format.html { render action: 'new' }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /users/1
  # PATCH/PUT /users/1.json
  def update
    respond_to do |format|
      if @user.update(user_params)
        format.html { redirect_to @user, notice: 'User was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /users/1
  # DELETE /users/1.json
  def destroy
    @user.destroy
    respond_to do |format|
      format.html { redirect_to users_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_user
      @user = User.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def user_params
      params.require(:user).permit(:name, :pin)
    end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/pics_helper.rb
module PicsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Rserv</title>
  <%= stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true %>
  <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
  <meta name="viewport" content="width=450">
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/pics/_form.html.erb
<%= form_for(@pic) do |f| %>
  <% if @pic.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@pic.errors.count, "error") %> prohibited this pic from being saved:</h2>

      <ul>
      <% @pic.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :src %><br>
    <%= f.text_area :src %>
  </div>
  <div class="field">
    <%= f.label :mot %><br>
    <%= f.text_field :mot %>
  </div>
  <div class="field">
    <%= f.label :sender %><br>
    <%= f.text_field :sender %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/pics/edit.html.erb
<h1>Editing pic</h1>

<%= render 'form' %>

<%= link_to 'Show', @pic %> |
<%= link_to 'Back', pics_path %>

app/views/pics/index.html.erb
<h1>Listing pics</h1>

<table>
  <thead>
    <tr>
      <th>Src</th>
      <th>Mot</th>
      <th>Sender</th>
      <th></th>
      <th></th>
      <th></th>
    </tr>
  </thead>

  <tbody>
    <% @pics.each do |pic| %>
      <tr>
        <td><img src="<%= pic.src %>" /></td>
        <td><%= pic.mot %></td>
        <td><%= pic.sender %></td>
        <td><%= link_to 'Show', pic %></td>
        <td><%= link_to 'Edit', edit_pic_path(pic) %></td>
        <td><%= link_to 'Destroy', pic, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Pic', new_pic_path %>

app/views/pics/multi.html.erb
<h1>Listing pics</h1>

<table>
  <thead>
    <tr>
      <th>Src</th>
      <th>Mot</th>
      <th>Sender</th>
      <th></th>
      <th></th>
      <th></th>
    </tr>
  </thead>

  <tbody>
    <% @pics.each do |pic| %>
      <tr>
        <td><img src="<%= pic.src %>" /></td>
        <td><%= pic.mot %></td>
        <td><%= pic.sender %></td>
        <td><%= link_to 'Show', pic %></td>
        <td><%= link_to 'Edit', edit_pic_path(pic) %></td>
        <td><%= link_to 'Destroy', pic, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Pic', new_pic_path %>

app/views/pics/new.html.erb
<h1>New pic</h1>

<%= render 'form' %>

<%= link_to 'Back', pics_path %>

app/views/pics/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Src:</strong>
  <img src="data:image/png;base64,<%= @pic.src %>" />
  <img src="<%= @pic.src %>" />

  
</p>

<p>
  <strong>Mot:</strong>
  <%= @pic.mot %>
</p>

<p>
  <strong>Sender:</strong>
  <%= @pic.sender %>
</p>

<%= link_to 'Edit', edit_pic_path(@pic) %> |
<%= link_to 'Back', pics_path %>

app/views/users/_form.html.erb
<%= form_for(@user) do |f| %>
  <% if @user.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@user.errors.count, "error") %> prohibited this user from being saved:</h2>

      <ul>
      <% @user.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :pin %><br>
    <%= f.text_field :pin %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/users/edit.html.erb
<h1>Editing user</h1>

<%= render 'form' %>

<%= link_to 'Show', @user %> |
<%= link_to 'Back', users_path %>

app/views/users/hello.html.erb
<center>
	<br><br><br><br><br>
<h1>Hello <%= @user.name %></h1>
</center>

app/views/users/hello_new.html.erb
<CENTER>
<br><br><br><br>
<h2>Guess/Draw</h2>
<h4>This is your first time here, can register please </h4>
<br><br><br>

<%= form_for(@user) do |f| %>
  <% if @user.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@user.errors.count, "error") %> prohibited this user from being saved:</h2>

      <ul>
      <% @user.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <label for="user_name">Username</label><br>
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :pin %><br>
    <input id="user_pin" name="user[pin]" type="text" value="<%= @pin %>" readonly/>
  </div>
  <div class="actions">
    <%= f.submit "Register"%>
  </div>
<% end %>
</CENTER>

app/views/users/index.html.erb
<h1>Listing users</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Pin</th>
      <th></th>
      <th></th>
      <th></th>
    </tr>
  </thead>

  <tbody>
    <% @users.each do |user| %>
      <tr>
        <td><%= user.name %></td>
        <td><%= user.pin %></td>
        <td><%= link_to 'Show', user %></td>
        <td><%= link_to 'Edit', edit_user_path(user) %></td>
        <td><%= link_to 'Destroy', user, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New User', new_user_path %>

app/views/users/new.html.erb
<h1>New user</h1>

<%= render 'form' %>

<%= link_to 'Back', users_path %>

app/views/users/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @user.name %>
</p>

<p>
  <strong>Pin:</strong>
  <%= @user.pin %>
</p>

<%= link_to 'Edit', edit_user_path(@user) %> |
<%= link_to 'Back', users_path %>

app/views/welcome/index.html.erb
<h1>Welcome#index</h1>
<p>Find me in app/views/welcome/index.html.erb</p>